services:
  device_agent:
    image: spaneng/doover_device_agent:apps-multi-wss
    networks:
      - enip_network
    ports:
      - 49100:49100
      - 50051:50051
    environment:
      - WSS_ENDPOINT=wss://device_agent:50051/ws

  sim_generator:
    build: ./tag_values_generator
    networks:
      - enip_network
    restart: unless-stopped
    depends_on:
      - device_agent
    environment:
      - APP_KEY=sim_generator
      - HEALTHCHECK_PORT=49201
      - DDA_URI=device_agent:50051

  sim_reader:
    build: ./output_reader
    networks:
      - enip_network
    restart: unless-stopped
    depends_on:
      - device_agent
      - sim_generator
    environment:
      - APP_KEY=sim_reader
      - HEALTHCHECK_PORT=49202
      - DDA_URI=device_agent:50051
      - PLC_HOST=sample_application

  sample_application:
    build: ../
    networks:
      - enip_network
    ports:
      - 44818:44818
    restart: unless-stopped
    depends_on:
      - device_agent
      - sim_generator
    environment:
      - APP_KEY=test_app
      - DDA_URI=device_agent:50051
      - HEALTHCHECK_PORT=49203
      - CONFIG_FP=/app_config.json
    volumes:
      - ./app_config.json:/app_config.json

networks:
  enip_network:
    driver: bridge
