services:
  device_agent:
    image: spaneng/doover_device_agent:apps
    network_mode: host
    ports:
      - 49100:49100

  sim_generator:
    build: ./tag_values_generator
    network_mode: host
    restart: unless-stopped
    depends_on:
      - device_agent
    environment:
      - APP_KEY=sim_generator
      - HEALTHCHECK_PORT=49201

  sim_reader:
    build: ./output_reader
    network_mode: host
    restart: unless-stopped
    depends_on:
      - device_agent
      - sim_generator
    environment:
      - APP_KEY=sim_reader
      - HEALTHCHECK_PORT=49202

  sample_application:
    build: ../
    network_mode: host
    ports:
      - 44818:44818
    restart: unless-stopped
    depends_on:
      - device_agent
      - sim_generator
    environment:
      - APP_KEY=test_app
      - HEALTHCHECK_PORT=49203
      - CONFIG_FP=/app_config.json
    volumes:
      - ./app_config.json:/app_config.json
